name: Run Custom Badges Scripts

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Auth com token (GH_TOKEN)
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Permissão para scripts
        run: chmod +x galaxy_brain.sh starstruck.sh

      - name: Executa galaxy_brain.sh
        run: ./galaxy_brain.sh

      - name: Executa starstruck.sh
        run: ./starstruck.sh

  instalar-gh-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar GitHub CLI compatível (usando repo do jammy)
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |
            sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg

          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages jammy main" |
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

          sudo apt update
          sudo apt install gh -y
