name: Run Custom Badges Scripts

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Give permission to scripts
        run: chmod +x galaxy_brain.sh starstruck.sh
        shell: bash

      - name: Execute galaxy_brain.sh
        run: ./galaxy_brain.sh
        shell: bash

      - name: Execute starstruck.sh
        run: ./starstruck.sh
        shell: bash
